### PR TITLE
Mathys l patch opdracht info

### PR DESCRIPTION
**Pull request by MathysL**

### CODE REVIEW

**Comment by MathysL** [comment]
van master naar winc info pushen, readme opdracht

**Comment by MathysL** [comment]
comit ..pull master

**Comment by MathysL** [comment]
..

**Comment by nielsbom** [comment]
Hi @MathysL!
Cool that you _can_ make pull requests, but please refrain from that so your fellow students can write their own code and are not enticed to look at your solution :-)

**Pull request closed without merging**
